### ISSUE TITLE
Allow navigating to crates.io / relevant links

### ISSUE THREAD

**Issue by philippeitis** [TheMayoras/cratuity#4]
crates.io provides a lot of useful links in the search interface (to Homepage, Documentation, and Repository, and the actual page, which displays the README.md) - being able to immediately open these pages in the native browser, from the CLI, via a hotkey, would be very convenient. I'd imagine the hotkeys could be something like c for the crates.io page, h for the crate homepage, d for its documentation, and r for the repository. 

It would also be really nice to be able to open the README.md (as in what crates.io displays) inside the terminal (eg. via the Enter key), since it would make it easier to check if a particular crate provides the functionality you need. This repo (https://github.com/Canop/termimad) seems like it would make the rendering portion easier to implement.

**Comment by TheMayoras** [comment]
#7
Handled by PR
